### ISSUE TITLE
Mergeutil#merge chokes on arrays?

### ISSUE THREAD

**Issue by jamierocks** [Despector/ObfuscationMapper#4]
```
Exception in thread "main" java.lang.IllegalStateException: [Ljava/lang/String; is a descriptor not a type name
        at org.spongepowered.despector.ast.SourceSet.get(SourceSet.java:89)
        at org.spongepowered.obfuscation.merge.operation.MergeUtil.merge(MergeUtil.java:136)
        at org.spongepowered.obfuscation.merge.operation.MergeUtil.lambda$static$34(MergeUtil.java:907)
        at org.spongepowered.obfuscation.merge.operation.MergeUtil.merge(MergeUtil.java:215)
        at org.spongepowered.obfuscation.merge.operation.MergeUtil.lambda$static$21(MergeUtil.java:855)
        at org.spongepowered.obfuscation.merge.operation.MergeUtil.merge(MergeUtil.java:232)
        at org.spongepowered.obfuscation.merge.operation.MergeUtil.lambda$static$8(MergeUtil.java:503)
        at org.spongepowered.obfuscation.merge.operation.MergeUtil.merge(MergeUtil.java:198)
        at org.spongepowered.obfuscation.merge.operation.MergeUtil.merge(MergeUtil.java:118)
        at org.spongepowered.obfuscation.merge.operation.MergeMatchedMethods.operate(MergeMatchedMethods.java:40)
        at org.spongepowered.obfuscation.merge.MergeEngine.merge(MergeEngine.java:367)
        at org.spongepowered.obfuscation.ObfuscationMapper.main(ObfuscationMapper.java:264)
```
Perhaps a more unusual setting for obfuscationmapper, but I'm using beta 1.2 here.

**Comment by Deamon5550** [comment]
It needs to be updated for the latest despector changes
